spring.datasource.url=postgresql://portfolio_user:UPY6pl8hDWGytBdFQ3APIOZEx7xOJk2Z@dpg-d75f2jma2pns738shae0-a/portfolio_2ap2
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true